# Generated by Django 5.2.4 on 2025-08-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Food Bank', max_length=50)),
                ('locale', models.CharField(default='enUK', max_length=5)),
            ],
            options={
                'db_table': 'global_configuration',
            },
        ),
    ]
