# Generated by Django 5.2.4 on 2025-07-31 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableBenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'available_benefits',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('door_number', models.CharField(max_length=20)),
                ('address_line_1', models.CharField(max_length=50)),
                ('address_line_2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=30)),
                ('county', models.CharField(max_length=30)),
                ('post_code', models.CharField(max_length=10)),
                ('telephone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='ClientHouseholdBenefits',
            fields=[
                ('pk', models.CompositePrimaryKey('client_id', 'benefit_type_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('benefit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.availablebenefits')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
            options={
                'db_table': 'client_household_benefits',
            },
        ),
        migrations.CreateModel(
            name='ClientHouseholdMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_adults', models.IntegerField(default=0, null=True)),
                ('num_pensioners', models.IntegerField(default=0, null=True)),
                ('num_children_0_to_5', models.IntegerField(default=0, null=True)),
                ('num_children_6_to_11', models.IntegerField(default=0, null=True)),
                ('num_children_12_to_17', models.IntegerField(default=0, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
            options={
                'db_table': 'client_household_members',
            },
        ),
    ]
